create table if not exists changes (
  id bigint generated by default as identity primary key,
  table_name text not null,
  row_id bigint,
  action text not null,
  changed_at timestamptz default now()
);
