begin;

drop view if exists user_net_balance;
drop view if exists user_paid;
drop view if exists user_consumed;

alter table profiles
  add column id_bigint bigint generated by default as identity;

with ordered as (
  select
    id,
    row_number() over (order by created_at nulls last, id) as new_id
  from profiles
)
update profiles
set id_bigint = ordered.new_id
from ordered
where profiles.id = ordered.id;

do $$ begin
  if exists (select 1 from profiles where id_bigint is null) then
    raise exception 'profiles.id migration failed';
  end if;
end $$;

alter table profiles
  alter column id_bigint set not null;

select setval(
  pg_get_serial_sequence('profiles', 'id_bigint'),
  coalesce((select max(id_bigint) from profiles), 0)
);

alter table transactions
  add column id_bigint bigint generated by default as identity,
  add column payer_id_bigint bigint;

with ordered as (
  select
    id,
    row_number() over (order by created_at nulls last, id) as new_id
  from transactions
)
update transactions
set id_bigint = ordered.new_id
from ordered
where transactions.id = ordered.id;

update transactions
set payer_id_bigint = profiles.id_bigint
from profiles
where transactions.payer_id = profiles.id;

do $$ begin
  if exists (select 1 from transactions where id_bigint is null) then
    raise exception 'transactions.id migration failed';
  end if;
  if exists (select 1 from transactions where payer_id_bigint is null) then
    raise exception 'transactions.payer_id migration failed';
  end if;
end $$;

alter table transactions
  alter column id_bigint set not null,
  alter column payer_id_bigint set not null;

select setval(
  pg_get_serial_sequence('transactions', 'id_bigint'),
  coalesce((select max(id_bigint) from transactions), 0)
);

alter table transaction_splits
  add column id_bigint bigint generated by default as identity,
  add column transaction_id_bigint bigint,
  add column user_id_bigint bigint;

with ordered as (
  select
    id,
    row_number() over (order by id) as new_id
  from transaction_splits
)
update transaction_splits
set id_bigint = ordered.new_id
from ordered
where transaction_splits.id = ordered.id;

update transaction_splits
set transaction_id_bigint = transactions.id_bigint
from transactions
where transaction_splits.transaction_id = transactions.id;

update transaction_splits
set user_id_bigint = profiles.id_bigint
from profiles
where transaction_splits.user_id = profiles.id;

do $$ begin
  if exists (select 1 from transaction_splits where id_bigint is null) then
    raise exception 'transaction_splits.id migration failed';
  end if;
  if exists (select 1 from transaction_splits where transaction_id_bigint is null) then
    raise exception 'transaction_splits.transaction_id migration failed';
  end if;
  if exists (select 1 from transaction_splits where user_id_bigint is null) then
    raise exception 'transaction_splits.user_id migration failed';
  end if;
end $$;

alter table transaction_splits
  alter column id_bigint set not null,
  alter column transaction_id_bigint set not null,
  alter column user_id_bigint set not null;

select setval(
  pg_get_serial_sequence('transaction_splits', 'id_bigint'),
  coalesce((select max(id_bigint) from transaction_splits), 0)
);

alter table transaction_splits
  drop constraint if exists transaction_splits_transaction_id_fkey,
  drop constraint if exists transaction_splits_pkey;

alter table transactions
  drop constraint if exists transactions_pkey;

alter table profiles
  drop constraint if exists profiles_pkey;

alter table transaction_splits
  drop column transaction_id,
  drop column user_id,
  drop column id;

alter table transactions
  drop column payer_id,
  drop column id;

alter table profiles
  drop column id;

alter table profiles
  rename column id_bigint to id;

alter table transactions
  rename column id_bigint to id;

alter table transactions
  rename column payer_id_bigint to payer_id;

alter table transaction_splits
  rename column id_bigint to id;

alter table transaction_splits
  rename column transaction_id_bigint to transaction_id;

alter table transaction_splits
  rename column user_id_bigint to user_id;

alter table profiles
  add primary key (id);

alter table transactions
  add primary key (id);

alter table transaction_splits
  add primary key (id),
  add constraint transaction_splits_transaction_id_fkey
    foreign key (transaction_id) references transactions(id) on delete cascade;

create or replace view user_consumed as
select
  user_id,
  sum(amount) as total_consumed
from transaction_splits
group by user_id;

create or replace view user_paid as
select
  payer_id as user_id,
  sum(amount) as total_paid
from transactions
group by payer_id;

create or replace view user_net_balance as
select
  coalesce(user_paid.user_id, user_consumed.user_id) as user_id,
  coalesce(user_paid.total_paid, 0) - coalesce(user_consumed.total_consumed, 0) as net_balance
from user_paid
full join user_consumed on user_paid.user_id = user_consumed.user_id;

commit;
