create table if not exists profiles (
  id bigint generated by default as identity primary key,
  display_name text,
  default_split numeric(5, 2) default 0.5,
  created_at timestamptz default now()
);

do $$ begin
  create type transaction_type as enum ('EXPENSE', 'INCOME', 'LIQUIDATION');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type split_mode as enum ('custom', 'none', 'owed');
exception
  when duplicate_object then null;
end $$;

create table if not exists transactions (
  id bigint generated by default as identity primary key,
  payer_id bigint not null,
  beneficiary_id bigint,
  split_mode split_mode not null default 'custom',
  amount numeric(12, 2) not null,
  category text,
  date date not null,
  note text,
  type transaction_type not null,
  created_at timestamptz default now()
);

create table if not exists transaction_splits (
  id bigint generated by default as identity primary key,
  transaction_id bigint references transactions(id) on delete cascade,
  user_id bigint not null,
  amount numeric(12, 2) not null
);

create or replace view user_paid as
select
  payer_id as user_id,
  sum(amount) as total_paid
from transactions
where type in ('EXPENSE', 'LIQUIDATION')
group by payer_id;

create or replace view user_consumed as
select
  user_id,
  sum(amount) as total_consumed
from (
  select
    transaction_splits.user_id,
    transaction_splits.amount
  from transaction_splits
  join transactions on transactions.id = transaction_splits.transaction_id
  where transactions.type = 'EXPENSE' and transactions.split_mode = 'custom'
  union all
  select
    transactions.beneficiary_id as user_id,
    transactions.amount
  from transactions
  where transactions.type = 'EXPENSE' and transactions.split_mode = 'owed'
  union all
  select
    transactions.payer_id as user_id,
    transactions.amount
  from transactions
  where transactions.type = 'EXPENSE' and transactions.split_mode = 'none'
  union all
  select
    transactions.beneficiary_id as user_id,
    transactions.amount
  from transactions
  where transactions.type = 'LIQUIDATION'
) consumption
where user_id is not null
group by user_id;

create or replace view user_net_balance as
select
  coalesce(user_paid.user_id, user_consumed.user_id) as user_id,
  coalesce(user_paid.total_paid, 0) - coalesce(user_consumed.total_consumed, 0) as net_balance
from user_paid
full join user_consumed on user_paid.user_id = user_consumed.user_id;
